CREATE TABLE `users` (
  `user_id` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `provider` varchar(15) NOT NULL,
  `nickname` varchar(100) NOT NULL,
  `role` varchar(15) NOT NULL,
  `birth_year` int NOT NULL,
  `birth_month` int NOT NULL,
  `school` varchar(30) NOT NULL,
  `score` int NOT NULL,
  `score_range` varchar(15) NOT NULL,
  `graduate_date` int NOT NULL,
  `graduate_month` int NOT NULL,
  `major` varchar(50) NOT NULL,
  `sub_major` varchar(50) DEFAULT NULL,
  `minor` varchar(50) DEFAULT NULL,
  `company` varchar(100) DEFAULT NULL,
  `field` varchar(255) NOT NULL,
  `tech_stack` varchar(255) NOT NULL,
  `awards` text,
  `activity` text,
  `career` text,
  `certificate` text,
  `img_url` varchar(255) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `modified_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `UniqueNickName` (`nickname`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci